apiVersion: v1
kind: Namespace
metadata:
  name: wp-ns

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: wp-configmap
  namespace: wp-ns
data:
  WORDPRESS_DB_HOST: "my-service.db-ns.svc.cluster.local"
  WORDPRESS_DB_USER: "wordpress"
  WORDPRESS_DB_NAME: "wordpress"

---

apiVersion: v1
kind: Secret
metadata:
  name: wp-secret
  namespace: wp-ns
type: Opaque
data:
  WORDPRESS_DB_PASSWORD: d29yZHByZXNz

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-app
  namespace: wp-ns
  labels:
    app: wordpress-app
    version: v1
    env: dev
spec:
  replicas: 5
  selector:
    matchLabels:
      app: wordpress-app
  template:
    metadata:
      labels:
        app: wordpress-app
    spec:
      containers:
        - name: wordpress-app
          image: wordpress:latest
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: wp-configmap
            - secretRef:
                name: wp-secret

---

apiVersion: v1
kind: Service
metadata:
  name: my-cluster-lb-service
  namespace: wp-ns
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 80
  selector:
    app: wordpress-app
