apiVersion: v1
kind: ConfigMap
metadata:
  name: wp-configmap
  namespace: wp-ns
data:
  WORDPRESS_DB_HOST: "my-service.db-ns.svc.cluster.local"
  WORDPRESS_DB_USER: "wordpress"
  WORDPRESS_DB_NAME: "wordpress"


