#apiVersion: v1
#kind: ConfigMap
#metadata:
#  name: db-configmap
#  namespace: wp-ns
#data:
#  MYSQL_DATABASE: "wordpress"
#  MYSQL_USER: "wordpress"
#
#---
#
#apiVersion: v1
#kind: Secret
#metadata:
#  name: db-secret
#  namespace: wp-ns
#type: Opaque
#data:
#  MYSQL_ROOT_PASSWORD: c29tZXdvcmRwcmVzcw==
#  MYSQL_PASSWORD: d29yZHByZXNz
#
#---
#
#apiVersion: v1
#kind: ConfigMap
#metadata:
#  name: wp-configmap
#  namespace: wp-ns
#data:
#  WORDPRESS_DB_HOST: "my-service.wp-ns.svc.cluster.local"
#  WORDPRESS_DB_USER: "wordpress"
#  WORDPRESS_DB_NAME: "wordpress"
#
#
#---
#
#apiVersion: v1
#kind: Secret
#metadata:
#  name: wp-secret
#  namespace: wp-ns
#type: Opaque
#data:
#  WORDPRESS_DB_PASSWORD: d29yZHByZXNz
#
#---
#
#apiVersion: apps/v1
#kind: Deployment
#metadata:
#  name: database
#  namespace: wp-ns
#  labels:
#    app: database
#    version: v1
#    env: dev
#spec:
#  replicas: 1
#  selector:
#    matchLabels:
#      app: database
#  template:
#    metadata:
#      labels:
#        app: database
#    spec:
#      containers:
#        - name: database
#          image: mariadb:10.6.4-focal
#          ports:
#            - containerPort: 3306
#          volumeMounts:
#            - mountPath: /var/lib/mysql
#              name: mysql-persistent-storage
#          envFrom:
#            - secretRef:
#                name: db-secret
#            - configMapRef:
#                name: db-configmap
#      volumes:
#        - name: mysql-persistent-storage
#
#---
#
#apiVersion: apps/v1
#kind: Deployment
#metadata:
#  name: wordpress-app
#  namespace: wp-ns
#  labels:
#    app: wordpress-app
#    version: v1
#    env: dev
#spec:
#  replicas: 5
#  selector:
#    matchLabels:
#      app: wordpress-app
#  template:
#    metadata:
#      labels:
#        app: wordpress-app
#    spec:
#      containers:
#        - name: wordpress-app
#          image: wordpress:latest
#          ports:
#            - containerPort: 80
#          envFrom:
#            - configMapRef:
#                name: wp-configmap
#            - secretRef:
#                name: wp-secret
#
