apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-web
  namespace: default
  labels:
    app: nginx-web
    version: v1
    env: dev
spec:
  replicas: 5
  selector:
    matchLabels:
      app: nginx-web
  template:
    metadata:
      labels:
        app: nginx-web
    spec:
      containers:
        - name: task_01_nginx-web
          image: nginx:latest
          ports:
            - containerPort: 80
